### ISSUE TITLE
小米note无法使用

### ISSUE THREAD

**Issue by 1523789353** [solohsu/EdXposed#1]
小米note无法使用
MI NOTE can't use

MI NOTE LET (virgo) / Lineage16.0 Android9.0

**Comment by MlgmXyysd** [comment]
Please provide your system log.

**Comment by 1523789353** [comment]
The log https://pan.baidu.com/s/1O6ZNk_S7L1aW7tbF0dHAlA


Arm32 bootloop

**Comment by MlgmXyysd** [comment]
0.2.9.1 is releases, should fix bugs.

**Comment by MlgmXyysd** [comment]
issue先关了，有问题可以重新提交。
