### ISSUE TITLE
0.2.9还是开机卡第二屏诶

### ISSUE THREAD

**Issue by lecx1205** [solohsu/EdXposed#10]
lgv30刷的PE，0.2.8没问题，0.2.8.5和0.2.9都卡第二屏，这是log，
[bootloop-2017-03-01-12-24-24.log](https://github.com/solohsu/EdXposed/files/2783093/bootloop-2017-03-01-12-24-24.log)

**Comment by MlgmXyysd** [comment]
0.2.9.1 should fix these bugs.

**Comment by MlgmXyysd** [comment]
BTW, please use issue template(Desktop version is displayed).
