### ISSUE TITLE
[BUG] pixel3 最新系统 2.8.5及之后版本激活xposed edge无法正常开机

### ISSUE THREAD

**Issue by anyin233** [solohsu/EdXposed#18]
**什么情况/What happened?**
激活xposed edge后无法开机

**Xposed模块列表/Xposed Module List**
仅激活xposed edge和Google app助手

**Magisk模块列表/Magisk Module List**

![screenshot_20190124095812](https://user-images.githubusercontent.com/35858233/51650109-f0c37000-1fc1-11e9-9daa-592e8fc5dc6f.jpg)

![screenshot_20190124095832](https://user-images.githubusercontent.com/35858233/51650122-ffaa2280-1fc1-11e9-9005-1a028be342a6.jpg)

**系统型号、版本及xp版本/Versions**
pixel 3 - 9.0-系统具体版本：PQ1A.190105.004-安全补丁19年1月5日-出现问题的版本：2.8.5及以后
**相关Logcat/Logcat**
有助于定位问题/It can help us to locate issue

**Comment by MlgmXyysd** [comment]
Please provide your boot log.

**Comment by anyin233** [comment]
[bootloop-2019-01-24-10-42-33.log](https://github.com/solohsu/EdXposed/files/2790016/bootloop-2019-01-24-10-42-33.log)
[bootloop-2019-01-24-10-47-02.log](https://github.com/solohsu/EdXposed/files/2790017/bootloop-2019-01-24-10-47-02.log)
[bootloop-2019-01-24-10-52-16.log](https://github.com/solohsu/EdXposed/files/2790018/bootloop-2019-01-24-10-52-16.log)
以上为boot log

**Comment by MlgmXyysd** [comment]
issue已关闭，更新到最新版再重新提交
