### ISSUE TITLE
support Android x86 and x86_64

### ISSUE THREAD

**Issue by youling257** [solohsu/EdXposed#2]
Androidx86 8.1 release, Bliss os x86 9.0 beta.
please build i386 and x86_64 version, i386 for 32bit Androidx86, x86_64 for 64bit Androidx86.

**Comment by MlgmXyysd** [comment]
That's limit by riru, Rikka not provide x86 or x64 arch builds.

**Comment by MlgmXyysd** [comment]
Riru now support x86/x64, EdXposed will soon.

**Comment by solohsu** [comment]
Should have been fixed by 4fc020501d12f43b880966047c1966dd25384c69
