### ISSUE TITLE
[BUG]华为Mate20 Pro EMUI9 加载 edxposed 以后，不生效

### ISSUE THREAD

**Issue by yishisanren** [solohsu/EdXposed#21]
**什么情况/What happened?**

在 magisk 中，加载了 edxposed，但重启后，xposed 提示框架没有安装。

**Magisk模块列表/Magisk Module List**

只有RIRU V11和 edxposed 从0.1-0.2.91都试过了。

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**
[bootloop-2019-01-23-22-57-51.log](https://github.com/solohsu/EdXposed/files/2794324/bootloop-2019-01-23-22-57-51.log)
有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
已知华为和三星未知毒性，问题已记录。
