### ISSUE TITLE
[BUG] EdXp + 幸运破解器模块 导致 Lawnchair V2 启动器持续崩溃

### ISSUE THREAD

**Issue by CatMe0w** [solohsu/EdXposed#22]
**什么情况/What happened?**

启用幸运破解器内置的 Xposed 模块时，桌面启动器 Lawnchair V2 （版本号 alpha-808） 将持续崩溃。

**Xposed模块列表/Xposed Module List**

幸运破解器 8.1.4

**Magisk模块列表/Magisk Module List**

https://imgur.com/a/5ey3JnN

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.2.9.1

Riru: 10

**相关Logcat/Logcat**

https://del.dog/axarunebes

**Comment by CatMe0w** [comment]
是的。

PS：“核心破解”模块(com.coderstory.toolkit)无法正常使用，启用这一模块会使包管理器无法更新任意应用，这应该是模块自身的问题，所以尝试幸运破解器模块。

**Comment by MlgmXyysd** [comment]
群文件上传了1.2.0的核心破解模块，幸运破解器并不支持9.0（貌似），建议您更新下模块试试。

**Comment by solohsu** [comment]
请尝试 v0.2.9.7 如果依然有问题，使用 https://github.com/solohsu/EdXpManager/releases，点击列表中的 Lawnchair 启动器应用，清除已编译状态，然后再以 speed 模式编译。
