### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by willie91** [solohsu/EdXposed#23]
**什么情况/What happened?**

无法开机

**Xposed模块列表/Xposed Module List**

xposed edge pro

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.29开始，一启用xposed edge pro就无法开机

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
模板不完整，关键信息缺失。
