### ISSUE TITLE
[BUG] 核心破解导致installer检测不到框架

### ISSUE THREAD

**Issue by weigeloveu** [solohsu/EdXposed#28]
**什么情况/What happened?**
激活核心破解模块会导致installer检测不到框架

**Xposed模块列表/Xposed Module List**

微x
qx
音量增强
核心破解

**Magisk模块列表/Magisk Module List**

riru core 11
edxposed 0.2.9.5

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.2.9.5

Riru:11

**相关Logcat/Logcat**

。。。识别不出框架的log，怎么抓。开启核心破解重启抓一下吗？

**Comment by MlgmXyysd** [comment]
抓开机log。

**Comment by weigeloveu** [comment]
我感觉应该是抓开机过程的log，可惜身边没电脑，用magisk boot loop log抓了一个
[bootloop-1970-01-19-03-57-29.zip](https://github.com/solohsu/EdXposed/files/2799609/bootloop-1970-01-19-03-57-29.zip)

**Comment by solohsu** [comment]
297应该修复了
