### ISSUE TITLE
[BUG]2.9.6音量增强失效

### ISSUE THREAD

**Issue by BoBppy** [solohsu/EdXposed#33]
什么情况/What happened?

网易云版本5.5.2
在0.2.9.6时，0.0.28音量增强器无法使用。
在0.2.9.5时，0.0.27可用

Xposed模块列表/Xposed Module List

允许截图/Screenshot allowed

![](https://i.imgur.com/LL2NMsT.png)

![](https://i.imgur.com/QfHixHZ.png)

Magisk模块列表/Magisk Module List

允许截图/Screenshot allowed

![](https://i.imgur.com/sfkipib.png)

![](https://i.imgur.com/7WLwP0C.png)

![](https://i.imgur.com/bPtJ1aT.png)

EdXposed及Riru版本/Versions of EdXposed and Riru

EdXposed:0.2.9.6

Riru:v11

相关Logcat/Logcat

![](https://i.imgur.com/PiwePqA.png)

这是在网易云内下载时，用matlog获取到的

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by BoBppy** [comment]
补充：MDWechat也失效

**Comment by zhenchao** [comment]
你是否在Edxp Manager中启用了白名单模式并且没有把该xp模块注入的对应应用列入白名单？

**Comment by solohsu** [comment]
试试297

**Comment by solohsu** [comment]
如果依然有问题，可以尝试，用 https://github.com/solohsu/EdXpManager/releases
列表中搜索网易云音乐，单击，执行弹出菜单中的清除，再执行以speed模式编译。

**Comment by BoBppy** [comment]
@solohsu 其实我是这样的，当我关闭SELinux时，音量增强器就起效了。可能还是因为Android p的SELinux过于严格吧...
