### ISSUE TITLE
[BUG] 2.9及以后小米6X无法开机

### ISSUE THREAD

**Issue by sambell361** [solohsu/EdXposed#34]
**什么情况/What happened?**

小米6X，刷了pe9.0，刷入2.9及以后版本的magisk模块后无法开机

**Xposed模块列表/Xposed Module List**

绿色守护，google app助手

**Magisk模块列表/Magisk Module List**

riru core
riru location

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:1.7.6

Riru:V10

**相关Logcat/Logcat**

SORRY NO

**Comment by solohsu** [comment]
应该是绿色守护引起的。重新提个issue，并附上开机logcat，不然没法定位解决。

**Comment by sambell361** [comment]
进不了系统界面如何抓log啊？还是你需要的是现在可以正常的开机log？
