### ISSUE TITLE
0.296 一加6 氧 os9.03 框架未安装

### ISSUE THREAD

**Issue by Palpitace** [solohsu/EdXposed#37]
![screenshot_20190128-003700 1](https://user-images.githubusercontent.com/38103793/51804485-96196500-229c-11e9-8099-fb4fa4347da3.jpg)

[android_boot.log](https://github.com/solohsu/EdXposed/files/2800306/android_boot.log)
大概在1点23分

**Comment by kwaiching** [comment]
我的也是這樣子 一加5T 氧OS 9.0.3

**Comment by kwaiching** [comment]
log : File does not exist

**Comment by MlgmXyysd** [comment]
Please use issue template.
