### ISSUE TITLE
pseudo effect 

### ISSUE THREAD

**Issue by kalawy** [solohsu/EdXposed#44]
each of greenify and jasi patcher gets activated in the xposed app .. but after restart the jasi app and greenify dont  detect that it is active

**Comment by kalawy** [comment]
can't provide logs  ..  the steps to reproduce are above

**Comment by MlgmXyysd** [comment]
boot logs, use our module or adb.

**Comment by kalawy** [comment]
walk me through the boot logs via the module please :*
