### ISSUE TITLE
lucky patcher disables xposed virtually 

### ISSUE THREAD

**Issue by kalawy** [solohsu/EdXposed#45]
after enabling lucky patcher in xposed and restarting .. the xposed app detects that xposed isn't installed .. clearing xposed app data makes  it detect  that it's installed but enabling the module again and restarting gives the same result

**Comment by 1161467173** [comment]
Please install Xposed Installer-3.1.4 by dvdandroid
link:https://drive.google.com/file/d/1Yyf6oaha539O3UKZuVNEbFGvcWDxgyPc/view?usp=drivesdk

**Comment by kalawy** [comment]
that's the version i used to test

**Comment by MlgmXyysd** [comment]
Please use issue template and provide logs.

**Comment by kalawy** [comment]
can't send logs  ..  the above is the method to reproduce the bug

**Comment by solohsu** [comment]
I think v0.2.9.7 should have solved this problem, can you give it a try ?

**Comment by kalawy** [comment]
of course   will  report   shortly
