### ISSUE TITLE
EdXposed-Bridge java.lang.VerifyError

### ISSUE THREAD

**Issue by erkie24** [solohsu/EdXposed#46]
Hi, I tried to make a new xposed module. it worked well use rovo's xposed (with android oreo), but an error appears when I use EdXposed (with android pie). Are there any suggestions or solutions that I can try? Thanks.

E/EdXposed-Bridge: java.lang.VerifyError: Verifier rejected class EdHooker22: double EdHooker22.backup(java.lang.Object) failed to verify: double EdHooker22.backup(java.lang.Object): [0x17] register v4 has type Undefined but expected Double (Low Half) return-wide on invalid register v4 (declaration of 'EdHooker22' appears in Anonymous-DexFile@0x757061e000-0x757061e8dc)

**Comment by solohsu** [comment]
Can you provide the signature of method which you are going to hook ?

**Comment by erkie24** [comment]
I tried to hook location class android. Other hook seems works fine except this method. Here's the code :

private XC_MethodHook locationLatitude = new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(XC_MethodHook.MethodHookParam param) {
            }
        };

// the logcat error pointing to this code
XposedHelpers.findAndHookMethod("android.location.Location",
                lpparam.classLoader,
                "getLatitude",
                locationLatitude );

**Comment by solohsu** [comment]
OK, thank you. I'll take a look later. :)
