### ISSUE TITLE
[BUG] 重启后xposed提示未安装，手机小米8，系统MIUI10开发版

### ISSUE THREAD

**Issue by wangyanjie332** [solohsu/EdXposed#48]
**什么情况/What happened?**

安装成功后，xposed installer 绿色，勾选xposed模块，提示重启模块生效，重启后xposed installer 变红，无法使用

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:v0.2.9.6_beta

Riru:v11

**Comment by solohsu** [comment]
请使用 v0.2.9.7 ， 如果依然有问题，请重新开个issue并附上激活的模块列表和开机log。
