### ISSUE TITLE
EdXp + 幸运破解器模块 导致 Lawnchair V2 启动器持续崩溃

### ISSUE THREAD

**Issue by CatMe0w** [solohsu/EdXposed#8]
相关 Log: https://del.dog/vikebabugo

版本号：
Android 9 ，版本号 PQ1A.190105.004
AospExtended 6.2 （第三方 ROM）
Magisk 18.0
Riru Core v10
Ed Xposed 0.2.8.5
幸运破解器 8.1.4
Lawnchair V2 alpha-808

**Comment by CatMe0w** [comment]
0.2.9 存在同样问题
Log: https://del.dog/axaxetumat

**Comment by MlgmXyysd** [comment]
下次提交记得使用模板，你更新下0.2.9.1试试。

**Comment by MlgmXyysd** [comment]
issue先关了，有问题可以重新提交。
